" Copy to ~/.gvimrc or ~/_gvimrc.

" GUI specific settings
if has("gui_running")
    colorscheme vividchalk          " Set default color schema
    set guifont=Menlo:h15           " Set font family and font size
    set antialias                   " MacVim: smooth fonts
    set encoding=utf-8              " Use UTF-8 everywhere.

    " WINDOWS only settings
    if has("win32") || has("win64")
        " Disable tearoff menu entries
        let &guioptions = substitute(&guioptions, "t", "", "g")
        " Maximize window on startup 
        au GUIEnter * simalt ~x
    endif

    " Toolbar and scrollbar settings
    set guioptions-=T               " Toggle off the toolbar
    set guioptions-=r               " Toggle off the right-hand scrollbar
    set guioptions-=l               " Toggle off the left-hand scrollbar
    set guioptions-=b               " Toggle off the bottom scrollbar
    "set guioptions-=m              " Toggle off the menubar
    let do_syntax_sel_menu = 1      " Always show file types in menu
    set lines=60 columns=140        " Window dimensions
    "winpos 0 0                     " Set starting position of GUI window

endif

" Alt-Space is System menu
if has("gui") && (has("win32") || has("win64"))
    noremap  <silent> <M-Space> :simalt ~<CR>
    inoremap <silent> <M-Space> <C-O>:simalt ~<CR>
    cnoremap <silent> <M-Space> <C-C>:simalt ~<CR>
endif

